Repository witseie-elen4010/2023-group-lab-003, pull requests merged in 2023-05, with the labels that each got.

#46 Toggle password
  SRC/public/scripts/Login.js
  SRC/public/scripts/signup.js
  SRC/public/styles/Login.css
  SRC/public/styles/signup.css
  SRC/views/Login.ejs
  SRC/views/signup.ejs
  _tests_/signup.test.js
Labels: security, user-story

#50 Settings backend
  SRC/controllers/auth.controller.js
  SRC/public/scripts/settings.js
  SRC/public/scripts/signup.js
  SRC/public/styles/settings.css
  SRC/routes/main.routes.js
  SRC/views/account.html
  SRC/views/goodbye.ejs
  SRC/views/lecturerDashboard.ejs
  SRC/views/password.html
  SRC/views/settings.ejs
  SRC/views/settings.html
  SRC/views/studentDashboard.ejs
Labels: developer-sized-story

#53 Update times bug fix
  SRC/routes/main.routes.js
  SRC/views/lecturerDashboard.ejs
  SRC/views/update.ejs
Labels: bug

#55 Fixing test cases for deployment
  _tests_/signup.test.js
Labels: bug

#54 Add another lecturer to meeting
  SRC/controllers/auth.controller.js
  SRC/public/scripts/includeAnotherLecturer.js
  SRC/public/styles/includeAnotherLecturer.css
  SRC/routes/main.routes.js
  SRC/views/includeAnotherLecturer.ejs
  SRC/views/lecturerDashboard.ejs
Labels: user-story

#56 Number of slots
  SRC/models/appointmentSchema.js
  SRC/public/styles/searchAppointment.css
  SRC/routes/main.routes.js
  SRC/views/searchAppointment.ejs
  SRC/views/studentDashboard.ejs
Labels: user-story

#78 Meeting status lecturer dashboard
  SRC/views/lecturerDashboard.ejs
Labels: user-story

#77 Flash errors search
  SRC/controllers/appointment.controller.js
  SRC/routes/main.routes.js
  SRC/views/searchAppointment.ejs
Labels: developer-sized-story
